systemLog:
   destination: file
   path: "~/tool/mongodb/27018/mongod.log"
   logAppend: true   # 必须设置为true、追加模式
   verbosity: 0      # 日志详细级别 (0-5, 0为默认)
   quiet: false      # 是否减少日志输出
   logRotate: reopen # 日志轮转方式: 'reopen' 或 'rename'
storage:
   dbPath: "~/tool/mongodb/27018/data" # 数据文件存储目录
   journal:
      enabled: true # 是否启用预写日志（Write-Ahead Logging）
      engine: wiredTiger # 存储引擎 ('wiredTiger', 'inMemory')
   wiredTiger:
      engineConfig:
         cacheSizeGB: 1 # 内存缓存大小 (GB)
         journalCompressor: snappy # 日志压缩算法
      collectionConfig:
         blockCompressor: snappy # 集合数据压缩算法
      indexConfig:
         prefixCompression: true # 索引前缀压缩
   inMemory:
      engineConfig:
         inMemorySizeGB: 1 # inMemory引擎专用
processManagement:
   fork: true        # 以守护进程（daemon）方式运行
   pidFilePath: "~/tool/mongodb/27018/mongod.pid"  # PID文件路径
net:
   bindIp: 0.0.0.0,192.168.1.100 # 绑定的IP地址列表
   port: 27018       # 监听端口
   maxIncomingConnections: 65536 # 最大并发连接数
   wireObjectCheck: true # 对客户端请求进行基本校验
   ipv6: false # 是否启用IPv6支持
   tls: # TLS/SSL加密配置
      mode: disabled # 'disabled', 'allowTLS', 'preferTLS', 'requireTLS'
      certificateKeyFile: /path/to/cert.pem
      CAFile: /path/to/ca.pem
replication:
  replSetName: "GuanGuoWei"


# 资料来源：https://cloud.tencent.com/developer/article/2653368