systemLog:
   destination: file
   path: "~/tool/mongodb/27018/mongod.log"
   logAppend: true
storage:
   dbPath: "~/tool/mongodb/27018/data"
processManagement:
   fork: true
   pidFilePath: "~/tool/mongodb/27018/mongod.pid"
net:
   bindIp: 0.0.0.0
   port: 27018
replication:
  replSetName: "GuanGuoWei"